apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: 192.168.56.138:5000/joelkhan/kubia-jsweb-unhealthy:v1
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080

