apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: 192.168.56.138:5000/joelkhan/kubia-jsweb:v1
        ports:
        - containerPort: 8080
